import type { Metadata } from "next";
import { InteriorHero, PageCTA, SiteFooter, SiteHeader } from "../site-chrome";

export const metadata: Metadata = { title: "Clean Water & Healthy Communities | Grassroots MI", description: "A Flint-rooted Grassroots MI campaign for safe water, accountability, and healthy Michigan communities." };

export default function CleanWaterPage() {
  return <main><SiteHeader />
    <InteriorHero eyebrow="Independent campaign · Flint and beyond" title="Clean water. Healthy" accent="communities." intro="No community should have to fight for safe drinking water. This campaign connects Flint's continuing story to infrastructure, accountability, public health, and dignity across Michigan." tone="gold" image="/media/images/p15-environmental-engineer-water-testing.webp?v=20260811-2" imageAlt="A worker in safety equipment examining a water sample beside a river." />
    <section className="water-story section"><div><p className="eyebrow">Why this matters</p><h2>Safe water is a right, not a privilege.</h2></div><div className="prose-large"><p>Flint showed Michigan and the nation what happens when communities are ignored, public systems fail, and accountability comes too late.</p><p>Grassroots MI supports community-led work that keeps affected residents at the center, demands transparent action, and connects water safety to the long-term health of neighborhoods.</p></div></section>
    <section className="water-pillars section"><div className="section-label"><span>Campaign focus</span><span>Three commitments</span></div><div className="pillar-grid"><article><span>01</span><h2>Safe Water</h2><p>Reliable access to safe drinking water and clear, trustworthy public information.</p></article><article><span>02</span><h2>Accountability</h2><p>Transparent decisions, responsible infrastructure investment, and consequences when systems fail.</p></article><article><span>03</span><h2>Healthy Neighborhoods</h2><p>Long-term public-health support and community control over the solutions that affect residents.</p></article></div></section>
    <section className="campaign-video section"><div><p className="eyebrow light">Water protection in motion</p><h2>Test. Report.<br />Protect people.</h2><p>Clear information and transparent testing help communities ask better questions and demand durable solutions.</p></div><video controls muted playsInline preload="metadata" poster="/media/video/posters/v08-scientist-water-testing-lake-poster.webp?v=20260811-2" aria-label="A scientist collecting and testing a water sample near a lake."><source src="/media/video/v08-scientist-water-testing-lake.mp4?v=20260811-2" type="video/mp4" />Your browser does not support hosted video.</video></section>
    <section className="campaign-path section"><div><p className="eyebrow light">How to stand with Flint</p><h2>Listen. Organize.<br />Act together.</h2></div><ol><li><span>01</span><div><strong>Learn from residents</strong><p>Center community experience and verified local information.</p></div></li><li><span>02</span><div><strong>Support local leadership</strong><p>Strengthen resident-led organizations and neighborhood networks.</p></div></li><li><span>03</span><div><strong>Demand durable solutions</strong><p>Advocate for safe infrastructure, public transparency, and continued accountability.</p></div></li></ol></section>
    <PageCTA eyebrow="Stand with Flint" title="Healthy communities need organized people." copy="Join the campaign, volunteer for outreach, or bring clean-water advocacy to your local chapter." primary="Join the campaign" />
    <SiteFooter />
  </main>;
}
